# name: Build and Push to ACR
# on:
#   push:
#     branches:
#       - dev
# jobs:
#   build:
#     name: 'Build and Push to ACR'
#     runs-on: ubuntu-latest

#     defaults:
#       run:
#         shell: bash

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: Docker Login
#         uses: azure/docker-login@v1
#         with:
#           login-server: ${{ secrets.ACR_URL }}
#           username: ${{ secrets.ACR_USERNAME }}
#           password: ${{ secrets.ACR_PASSWORD }}

#       - name: Build and Push to ACR
#         uses: docker/build-push-action@v2
#         with:
#           push: true
#           tags: ${{ secrets.ACR_URL }}/Frontend:latest
#           file: Frontend/Dockerfile
name: Build and Push to ACR
on:
  push:
    branches:
      - dev
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: 'Build and Push to ACR'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: Azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
      # - name: Login to azure
      # uses: azure/login@v1
      # with:
      #      creds: '{"clientId":"${{ env.ARM_CLIENT_ID }}","clientSecret":"${{ env.ARM_CLIENT_SECRET }}","subscriptionId":"${{ env.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ env.ARM_TENANT_ID }}"}'
      #      enable-AzPSSession: true

      # - name: Docker Login
      #   uses: azure/docker-login@v1
      #   with:
      #     login-server: ${{ secrets.ACR_URL }}
      #     username: ${{ secrets.ACR_USERNAME }}
      #     password: ${{ secrets.ACR_PASSWORD }}

      # - name: Set AKS Cluster Context
      #   uses: azure/aks-set-context@94ccc775c1997a3fcfbfbce3c459fec87e0ab188
      #   with:
      #     client-id: ${{ secrets.AZURE_CLIENT_ID }}
      #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      #     enable-AzPSSession: true
      #     cluster-name: testcluster
      #     resource-group: testrg

      # - name: Build and Push to ACR
      #   uses: docker/build-push-action@v2
      #   with:
      #     push: true
      #     tags: ${{ secrets.ACR_URL }}/backend:latest
      #     file: backend/Dockerfile

      # - name: Build and Push to ACR
      #   uses: docker/build-push-action@v2
      #   with:
      #     push: true
      #     tags: ${{ secrets.ACR_URL }}/frontend:latest
      #     file: frontend/Dockerfile


      # - name: Deploy to Backend Deploy
      #   run: kubectl apply -f backend/deployment.yaml

      # - name: Deploy to Backend Service
      #   run: kubectl apply -f backend/service.yaml

      # - name: Deploy to Frontend Deploy
      #   run: kubectl apply -f frontend/deployment.yaml

      # - name: Deploy to Frontend Service
      #   run: kubectl apply -f frontend/service.yaml
